"""What lives in each area, and how much of it a trainer already owns.

Built from `knowledge/maps/encounters.json` (generated by
`tools/build_pokeapi_knowledge.py`). Without it, "faltar espécies nesta área" is
a feeling; with it, it is a number.

The completionist's target is deliberately **not** 100% from the start. Early
Kanto simply cannot be completed: Surf and the fishing rods gate whole encounter
tables, and a bot that refuses to leave Route 1 until it has every species there
never reaches the rods that would let it. So the early target is a fraction, and
only after the League does area completion become literal.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ENCOUNTERS_PATH = Path(__file__).parent / "knowledge" / "maps" / "encounters.json"

# The target is everything the run can currently meet — no fraction, no quota.
# A fraction was only ever a stand-in for "the area holds things I cannot reach
# yet"; now that the encounter method answers that exactly, the honest target is
# all of it. The set itself grows when Surf and the rods arrive, so the same
# area is asked again later without ever demanding the impossible.
AREA_TARGET = 1.0

# At or below this chance, an encounter is the area's rarity, not its filler.
# Viridian Forest: Pikachu 5%, Caterpie 45%.
RARE_ENCOUNTER_CHANCE = 15

# The RAM map names and the PokéAPI slugs disagree in a handful of places that
# no rule would ever reconcile.
AREA_ALIASES = {
    "mt moon route 3": "mt-moon-1f",
    "route 2 gate north": "kanto-route-2-area",
    "route 2 gate south": "kanto-route-2-area",
    "viridian forest gate south": "viridian-forest-area",
    "viridian forest gate north": "viridian-forest-area",
}

_cache = None


def _areas():
    global _cache
    if _cache is None:
        try:
            with ENCOUNTERS_PATH.open("r", encoding="utf-8") as handle:
                _cache = json.load(handle).get("areas") or {}
        except (OSError, ValueError):
            # Missing knowledge is not a reason to stop a journey; it only means
            # the completionist falls back to "every new species".
            _cache = {}
    return _cache


def _slug(map_name):
    return re.sub(r"[^a-z0-9]+", "-", str(map_name).lower()).strip("-")


def area_key(map_name):
    """PokéAPI area slug for a RAM map name, or None when it has no table."""
    areas = _areas()
    if not areas:
        return None
    alias = AREA_ALIASES.get(str(map_name).lower())
    if alias in areas:
        return alias
    slug = _slug(map_name)
    for candidate in (f"{slug}-area", slug, f"kanto-{slug}-area", f"kanto-{slug}"):
        if candidate in areas:
            return candidate
    return None


def unlocked_methods(badges):
    """Encounter methods a trainer can actually use at this point of the story.

    Rare and impossible are different things, and the encounter method is what
    tells them apart: a species that only appears while surfing does not exist
    for a trainer without Surf, and counting it would leave the completionist
    chasing an area it cannot finish.

    Badges are the gate we can read from RAM with no ambiguity. Surf needs the
    Soul Badge to be used outside battle; the rods are sold/given along the same
    stretch of the story, so their badge counts are the honest approximation of
    "the run has reached that point".
    """
    badges = int(badges or 0)
    methods = {"walk", "gift", "gift-egg", "only-one"}
    if badges >= 3:      # Vermilion: Old Rod
        methods.add("old-rod")
    if badges >= 5:      # Soul Badge: Surf fora de batalha, e Good Rod em Fuchsia
        methods.update({"surf", "good-rod"})
    if badges >= 6:      # Super Rod, Rota 12
        methods.add("super-rod")
    return methods


def area_species(map_name, badges=None):
    """Species ids obtainable in this area, filtered by what the run can do.

    ``badges=None`` means "everything the area holds", which is the right answer
    for a catalogue and the wrong one for a target.
    """
    key = area_key(map_name)
    if key is None:
        return set()
    allowed = None if badges is None else unlocked_methods(badges)
    species = set()
    for entry in _areas()[key].values():
        if not entry.get("species_id"):
            continue
        methods = set(entry.get("methods") or ["walk"])
        if allowed is not None and not methods & allowed:
            continue
        species.add(int(entry["species_id"]))
    return species


def area_coverage(map_name, owned_species, badges=None):
    """How much of the *reachable* part of this area is already registered.

    Returns ``None`` when the area has nothing this run can meet — a city with
    no grass, or a lake for a trainer with no rod, is not an area a
    completionist can fail at.
    """
    species = area_species(map_name, badges)
    if not species:
        return None
    owned = species & {int(value) for value in owned_species}
    return {
        "area": area_key(map_name),
        "owned": len(owned),
        "total": len(species),
        "fraction": len(owned) / len(species),
        "missing": sorted(species - owned),
    }


def encounter_chance(map_name, species_id, badges=None):
    """Chance of meeting this species here, in percent; 0 when out of reach."""
    key = area_key(map_name)
    if key is None:
        return 0
    allowed = None if badges is None else unlocked_methods(badges)
    for entry in _areas()[key].values():
        if int(entry.get("species_id") or 0) != int(species_id):
            continue
        methods = set(entry.get("methods") or ["walk"])
        if allowed is not None and not methods & allowed:
            return 0
        return int(entry.get("chance") or 0)
    return 0


def is_rare_here(map_name, species_id, threshold=RARE_ENCOUNTER_CHANCE, badges=None):
    """Whether meeting this species here is the exception, not the rule.

    Pikachu is 5% of Viridian Forest against Caterpie's 45%. Walking away from
    the 5% because the area quota is already met is how a completionist ends the
    game without the one Pokémon the area is remembered for.
    """
    chance = encounter_chance(map_name, species_id, badges)
    return 0 < chance <= threshold


SPECIES_PATH = Path(__file__).parent / "knowledge" / "species.json"

_species_cache = None


def _species():
    global _species_cache
    if _species_cache is None:
        try:
            with SPECIES_PATH.open("r", encoding="utf-8") as handle:
                _species_cache = json.load(handle).get("species") or {}
        except (OSError, ValueError):
            _species_cache = {}
    return _species_cache


def species_types(species_id):
    """Types of a species, as a set. Empty when the table is missing."""
    entry = _species().get(str(int(species_id))) or {}
    return {str(name) for name in entry.get("types") or []}


def species_of_types(map_name, wanted_types, badges=None):
    """Reachable species here that match any of these types.

    A themed trainer needs to know where its team actually lives: in Blue there
    is almost no fire or dragon before Route 7, and none at all in the early
    routes. This turns "procurar fogo" into a fact about the current map instead
    of a hope.
    """
    wanted = {str(name) for name in wanted_types or ()}
    if not wanted:
        return set()
    return {
        species_id for species_id in area_species(map_name, badges)
        if species_types(species_id) & wanted
    }


def area_target(badges=None):
    """Completion target: everything reachable, at every stage of the run.

    Kept as a function because the caller reads better asking for the target
    than hardcoding a constant, and because what counts as reachable is already
    a function of how far the run has come.
    """
    return AREA_TARGET
