"""What lives in each area, and how much of it a trainer already owns.

Built from `knowledge/maps/encounters.json` (generated by
`tools/build_pokeapi_knowledge.py`). Without it, "faltar espécies nesta área" is
a feeling; with it, it is a number.

The completionist's target is deliberately **not** 100% from the start. Early
Kanto simply cannot be completed: Surf and the fishing rods gate whole encounter
tables, and a bot that refuses to leave Route 1 until it has every species there
never reaches the rods that would let it. So the early target is a fraction, and
only after the League does area completion become literal.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ENCOUNTERS_PATH = Path(__file__).parent / "knowledge" / "maps" / "encounters.json"

# Before the League, the water and fishing halves of most areas are unreachable.
# Half of what an area offers is what a walking trainer can realistically get.
AREA_TARGET_EARLY = 0.5
AREA_TARGET_POSTGAME = 1.0
POSTGAME_BADGES = 8

# The RAM map names and the PokéAPI slugs disagree in a handful of places that
# no rule would ever reconcile.
AREA_ALIASES = {
    "mt moon route 3": "mt-moon-1f",
    "route 2 gate north": "kanto-route-2-area",
    "route 2 gate south": "kanto-route-2-area",
    "viridian forest gate south": "viridian-forest-area",
    "viridian forest gate north": "viridian-forest-area",
}

_cache = None


def _areas():
    global _cache
    if _cache is None:
        try:
            with ENCOUNTERS_PATH.open("r", encoding="utf-8") as handle:
                _cache = json.load(handle).get("areas") or {}
        except (OSError, ValueError):
            # Missing knowledge is not a reason to stop a journey; it only means
            # the completionist falls back to "every new species".
            _cache = {}
    return _cache


def _slug(map_name):
    return re.sub(r"[^a-z0-9]+", "-", str(map_name).lower()).strip("-")


def area_key(map_name):
    """PokéAPI area slug for a RAM map name, or None when it has no table."""
    areas = _areas()
    if not areas:
        return None
    alias = AREA_ALIASES.get(str(map_name).lower())
    if alias in areas:
        return alias
    slug = _slug(map_name)
    for candidate in (f"{slug}-area", slug, f"kanto-{slug}-area", f"kanto-{slug}"):
        if candidate in areas:
            return candidate
    return None


def area_species(map_name):
    """Species ids obtainable in this area, as an unordered set."""
    key = area_key(map_name)
    if key is None:
        return set()
    return {
        int(entry["species_id"])
        for entry in _areas()[key].values()
        if entry.get("species_id")
    }


def area_coverage(map_name, owned_species):
    """How much of this area is already registered.

    Returns ``None`` when the area has no encounter table at all — a city with
    no grass is not an area a completionist can fail at.
    """
    species = area_species(map_name)
    if not species:
        return None
    owned = species & {int(value) for value in owned_species}
    return {
        "area": area_key(map_name),
        "owned": len(owned),
        "total": len(species),
        "fraction": len(owned) / len(species),
        "missing": sorted(species - owned),
    }


def area_target(badges):
    """Completion target for the current stage of the run."""
    return AREA_TARGET_POSTGAME if int(badges or 0) >= POSTGAME_BADGES else AREA_TARGET_EARLY
